// <auto-generated />
using KnoWhere.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace KnoWhere.API.Data.Migrations
{
    [DbContext(typeof(KnoWhereContext))]
    partial class KnoWhereContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KnoWhere.API.Data.Entities.PlaceBucket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddDate");

                    b.Property<string>("EntertainmentBucketId");

                    b.Property<string>("RestaurantBucketId");

                    b.HasKey("Id");

                    b.ToTable("PlacesBucket");
                });
#pragma warning restore 612, 618
        }
    }
}
